[build]
  base    = "nuxt"
  publish = "nuxt/dist"
  command = "npm run generate"

[context.live]
  environment = { API_URL = 'https://api.leahwalker.me/rest/' }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
